"""API resource endpoint classes."""

from .accounts import AccountsResource
from .namelist import (
    ClassesResource,
    CompanyCurrenciesResource,
    CustomersResource,
    DepartmentsResource,
    EmployeesResource,
    ItemsResource,
    JournalCodesResource,
    PaymentMethodsResource,
    TaxAgenciesResource,
    TaxCodesResource,
    TaxRatesResource,
    TermsResource,
    VendorsResource,
)
from .system import (
    BudgetsResource,
    CompanyInfoResource,
    EntitlementsResource,
    ExchangeRatesResource,
    PreferencesResource,
    TaxServiceResource,
)
from .transactions import (
    AttachablesResource,
    BillPaymentsResource,
    BillsResource,
    CreditMemosResource,
    DepositsResource,
    EstimatesResource,
    InvoicesResource,
    JournalEntriesResource,
    PaymentsResource,
    PurchaseOrdersResource,
    PurchasesResource,
    RefundReceiptsResource,
    SalesReceiptsResource,
    TimeActivitiesResource,
    TransfersResource,
    VendorCreditsResource,
)

__all__ = [
    "AccountsResource",
    "AttachablesResource",
    "BillPaymentsResource",
    "BillsResource",
    "BudgetsResource",
    "ClassesResource",
    "CompanyCurrenciesResource",
    "CompanyInfoResource",
    "CreditMemosResource",
    "CustomersResource",
    "DepartmentsResource",
    "DepositsResource",
    "EmployeesResource",
    "EntitlementsResource",
    "EstimatesResource",
    "ExchangeRatesResource",
    "InvoicesResource",
    "ItemsResource",
    "JournalCodesResource",
    "JournalEntriesResource",
    "PaymentMethodsResource",
    "PaymentsResource",
    "PreferencesResource",
    "PurchaseOrdersResource",
    "PurchasesResource",
    "RefundReceiptsResource",
    "SalesReceiptsResource",
    "TaxAgenciesResource",
    "TaxCodesResource",
    "TaxRatesResource",
    "TaxServiceResource",
    "TermsResource",
    "TimeActivitiesResource",
    "TransfersResource",
    "VendorCreditsResource",
    "VendorsResource",
]
